using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace test_website
{
    public class Fa
    {
        public static readonly string LockedOut = "حساب کاربری شما بسته شده است";
        public static readonly string Failure = "نام کاربری یا کلمه عبور اشتباه وارد شده است";
        public static readonly string Error = "خطایی رخ داده است";
        public static readonly string AdminMgnt = "مدیریت مدیر";
        public static readonly string CreateAdmin = "افزودن مدیر";
        public static readonly string DifferentPassword = "کلمه ی عبور صحیح نیست";
        public static readonly string DuplicateUser = "نام کاربری یا شماره ی ملی تکراری است";
        public static readonly string Delete = "حذف";
        public static readonly string Edit = "ویرایش";
        public static readonly string DeleteAdmin = "آیا می خواهید {0} از لیست مدیران حذف شود؟";
        public static readonly string Yes = "بله";
        public static readonly string No = "خیر";
        public static readonly string Logout = "خروج از سیستم";
        public static readonly string Login = "ورود";
        public static readonly string Name = "نام و نام خانوادگی";
        public static readonly string System = "سیستم";
        public static readonly string EditAdmin = "ویرایش مدیر";
        public static readonly string CollegeMgnt = "مدیریت دانشکده";
        public static readonly string Save = "ذخیره";
        public static readonly string DuplicateCollege = "دانشکده قبلا ثبت شده است";
        public static readonly string CreateCollege = "افزودن دانشکده";
        public static readonly string DeleteCollege = " با حذف دانشکده ی {0} ،تمام گروه های آموزشی و گروه های پژوهشی وابسطه به آن نیز حذف خواهند شد. آیا می خواهید این دانشکده از لیست دانشکده ها حذف شود؟";
        public static readonly string EditCollege = "ویرایش دانشکده";
        public static readonly string EducationalGroupMgnt = "مدیریت گروه آموزشی";
        public static readonly string CreateEducationalGroup = "افزودن گروه آموزشی";
        public static readonly string DeleteEducationalGroup = "با حذف این گروه آموزشی ،تمام گروه های پژوهشی وابسطه به آن نیز حذف خواهند شد. آیا می خواهید گروه آموزشی {0} از لیست گروه های آموزشی دانشکده {1} حذف شود؟";
        public static readonly string EditEducationalGroup = "ویرایش گروه آموزشی";
        public static readonly string DuplicateEducationalGroup = "گروه آموزشی قبلا ثبت شده است";
        public static readonly string ResearchGroupMgnt = "مدیریت گروه های پژوهشی";
        public static readonly string CreateResearchGroup = "افزودن گروه پژوهشی";
        public static readonly string DuplicateResearchGroup = "گروه پژوهشی قبلا ثبت شده است";
        public static readonly string DeleteResearchGroup = "آیا می خواهید گروه پژوهشی {0} از لیست گروه های پژوهشی حذف شود؟";
        public static readonly string EditResearchGroup = "ویرایش گروه پژوهشی";
        public static readonly string EmployerMgnt = "مدیریت کارفرما";
        public static readonly string CreateEmployer = "افزودن کارفرما";
        public static readonly string Governmental = "دولتی";
        public static readonly string Non_Govermental = "غیردولتی";
        public static readonly string HalfPrivate = "نیمه خصوصی";
        public static readonly string Military = "نظامی/غیر نظامی";
        public static readonly string EmployerType = "نوع کارفرما";
        public static readonly string SecurityClass = "کلاس محرمانه";
        public static readonly string Secret = "محرمانه";
        public static readonly string Normal = "عادی";
        public static readonly string DuplicateEmployer = "کارفرما قبلا ثبت شده است";
        public static readonly string DeleteEmployer = "با حذف {0} از لیست کارفرمایان، تمام پروژه های این کارفرما نیز حذف خواهد شد. آیا می خواهید این کارفرما حذف شود؟";
        public static readonly string EditEmployer = "ویرایش کارفرما";
        public static readonly string ExecuterMgnt = "مدیریت مجری";
        public static readonly string CreateExecuter = "افزودن مجری";
        public static readonly string DuplicateExecuter = "مجری قبلا ثبت شده است";
        public static readonly string DeleteExecuter = "آیا می خواهید {0} از لیست مجریان حذف شود؟";
        public static readonly string EditExecuter = "ویرایش مجری";
        public static readonly string Staff = "مدیریت کارکنان";
        public static readonly string CreateStaff = "افزودن کارمند";
        public static readonly string DeleteStaff = "آیا می خواهید {0} از لیست کارکنان حذف شود؟";
        public static readonly string EditStaff = "ویرایش کارکنان";
        public static readonly string ProjectMgnt = "مدیریت پروژه";
        public const string RequiredUserName = "ورود نام کاربری الزامی است";
        public const string UserNameChar = "کاراکتر های مجاز نام کاربری شامل حروف انگلیسی و اعداد می باشد";
        public const string UserName = "نام کاربری";
        public const string RequiredPassword = "ورود کلمه ی عبور الزامی است";
        public const string PasswordChar = "کلمه ی عبور باید حداقل 6 کاراکتر باشد";
        public const string Password = "کلمه ی عبور";
        public const string RememberMe = "مرا به خاطر بسپار";
        public const string EnterName = "نام را وارد کنید";
        public const string EnterLastName = "نام خانوادگی را وارد کنید";
        public const string EnterNationalCode = "کد ملی را وارد کنید";
        public const string NationalChar = "کد ملی فقط شامل اعداد است";
        public const string NationalLength = "کد ملی باید 10 رقم باشد";
        public const string ConfirmPassword = "تکرار کلمه ی عبور";
        public const string SamePassword = "کلمه ی عبور و تکرار آن یکسان نیست";
        public const string FirstName = "نام";
        public const string LastName = "نام خانوادگی";
        public const string NationalCode = "کدملی";
        public const string RequiredCollegeName = "نام دانشکده را وارد کنید";
        public const string CollegeName = "نام دانشکده";
        public const string RequiredEducationalGroupName = "نام گروه آموزشی را وارد کنید";
        public const string EducationalGroupName = "نام گروه آموزشی";
        public const string RequiredResearchGroupName = "نام گروه پژوهشی را وارد کنید";
        public const string ResearchGroupName = "نام گروه پژوهشی";
        public const string EmployerName = "نام کارفرما";
        public const string RequiredEmployerName = "نام کارفرما را وارد کنید";
        public const string EnterMasterId = "شماره مجری را وارد کنید";
        public const string MasterId = "شماره استادی";
        public const string Email = "ایمیل";
        public const string RequiredEmail = "ورود ایمیل الزامی است";
        public const string EmailValidation = "ایمیل را اشتباه وارد کرده اید";
        public const string PhoneNumber = "شماره تلفن";
        public const string RequiredPhoneNumber = "شماره تلفن را اشتباه وارد کرده اید";
        public const string Explain = "توضیحات";
        public const string Title = "عنوان طرح";
        public const string RequiredTitle = "عنوان طرح را وارد کنید";
        public const string ProjectId = "شماره طرح";
        public const string RequiredProjectId = "شماره طرح را وارد کنید";
        public const string Price = "مبلغ طرح";
        public const string RequiredPrice = "مبلغ را وارد کنید";
        public const string OverHeadPrice = "مبلغ بالاسری را وارد کنید";
        public const string ReceivePrice = "مبلغ وصول شده";
        public const string RemainPrice = "مبلغ مانده";
        public const string PaymentPrice = "مبلغ پرداخت شده به مجری";
        public const string MainContractId = "شماره قرارداد اصلی";
        public const string RequiredMainContractId = "شماره قرارداد اصلی را وارد کنید";
        public const string MainContractDate = "تاریخ قرارداد اصلی";
        public const string RequiredMainContractDate = "تاریخ قرارداد اصلی را وارد کنید";
        public const string InternalContractId = "شماره قرارداد داخلی";
        public const string RequiredInternalContractId = "شماره قرارداد داخلی را وارد کنید";

    }
}